# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minishop', '0002_auto_20170130_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='quantity_backorder',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='minishop.Order'),
        ),
    ]
