# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minishop', '0003_auto_20170209_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity_backorder',
            field=models.PositiveIntegerField(),
        ),
    ]
