# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minishop', '0004_auto_20170209_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='partner_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='partner_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
