# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minishop', '0005_auto_20170210_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='mollie_payment_status',
        ),
    ]
