language: python
python:
  - "3.5"
services: postgresql
addons:
  postgresql: "9.4"
install: "pip install -r requirements.txt"
script: make test
before_script:
  - psql -c 'create database smokeyfeet;' -U postgres
