# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('num_offered', models.PositiveIntegerField()),
                ('require_partner', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MolliePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mollie_id', models.CharField(max_length=64, unique=True)),
                ('mollie_status', models.CharField(default='open', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PassType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('party', 'Party Pass'), ('full', 'Full Pass')], max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('order', models.PositiveIntegerField()),
                ('num_offered', models.PositiveIntegerField()),
                ('video_audition_required', models.BooleanField(default=False)),
                ('price', models.FloatField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dance_role', models.CharField(choices=[('leader', 'Leader'), ('follower', 'Follower')], default='leader', max_length=32)),
                ('residing_country', django_countries.fields.CountryField(max_length=2)),
                ('workshop_partner_name', models.CharField(blank=True, max_length=128)),
                ('workshop_partner_email', models.EmailField(blank=True, max_length=254)),
                ('strictly_partner', models.CharField(blank=True, max_length=128)),
                ('include_lunch', models.BooleanField(default=False)),
                ('diet_requirements', models.TextField(blank=True, max_length=140)),
                ('crew_remarks', models.TextField(blank=True, max_length=4096)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('competitions', models.ManyToManyField(blank=True, to='registration.CompetitionType')),
                ('pass_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.PassType')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=2048)),
                ('num_offered', models.PositiveIntegerField()),
                ('refund_amount', models.FloatField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='registration',
            name='volunteering_for',
            field=models.ManyToManyField(blank=True, to='registration.VolunteerType'),
        ),
        migrations.AddField(
            model_name='molliepayment',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Registration'),
        ),
    ]
