# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(default='open', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_status_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
