# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='molliepayment',
            name='mollie_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
