# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20161121_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='LunchType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('sort_order', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.RemoveField(
            model_name='registration',
            name='include_lunch',
        ),
        migrations.AlterField(
            model_name='registration',
            name='pass_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.PassType'),
        ),
        migrations.AddField(
            model_name='registration',
            name='lunch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='registration.LunchType'),
        ),
    ]
