# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20170101_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='audition_url',
            field=models.URLField(blank=True),
        ),
    ]
