# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_molliepayment_mollie_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payment_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
