# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20161128_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='payment_status_at',
            field=models.DateTimeField(null=True),
        ),
    ]
