# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20161128_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='passtype',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
