# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_passtype_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='lunch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.LunchType'),
        ),
    ]
