# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 19:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='passtype',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
