# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20161231_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
