# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationstatus',
            name='registration',
        ),
        migrations.AlterField(
            model_name='interaction',
            name='description',
            field=models.TextField(blank=True, max_length=4096),
        ),
        migrations.DeleteModel(
            name='RegistrationStatus',
        ),
    ]
